server:
  port: 18086
  servlet:
    context-path: /boot

spring:
  servlet:
    multipart:
      # 开启multipart上传功能
      enabled: true
      # 文件写入磁盘的阈值
      file-size-threshold: 2KB
      # 最大文件大小
      max-file-size: 10MB
      # 最大请求大小
      max-request-size: 10MB
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    dynamic:
      # 通过http://ip:port/boot/druid/index.html访问
      druid:
        # 初始化、最小、最大 值
        initial-size: 5
        min-idle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测,检测需要关闭的空闲连接,单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间,单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache,并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters,去掉后监控界面sql无法统计,'wall'用于防火墙
        filters: stat,wall,slf4j
        # 通过connectProperties属性来打开mergeSql功能,慢SQL记录
        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      datasource:
        #        master:
        #          url: jdbc:mysql://47.104.23.94:13306/sskj2?characterEncoding=UTF-8&useUnicode=true&useSSL=false&connectTimeout=6000000&socketTimeout=6000000&rewriteBatchedStatements=true
        #          username: root
        #          password: Kingtroldata1111@
        #          driver-class-name: com.mysql.jdbc.Driver
        #          master:
        #            url: jdbc:mysql://168.0.9.154:13306/sk-se-boot-fuzhou-new?characterEncoding=UTF-8&useUnicode=true&useSSL=false&connectTimeout=60000&socketTimeout=1800
        #            username: root
        #            password: jkauto@123fuzhou
        #            driver-class-name: com.mysql.jdbc.Driver
        master:
          url: jdbc:mysql://192.168.88.51:3306/sk-se-boot-ynlj?characterEncoding=UTF-8&useUnicode=true&useSSL=false&connectTimeout=60000000&socketTimeout=1800000
          username: root
          password: jkauto@123lj
          driver-class-name: com.mysql.jdbc.Driver
        ynlj-third:
          url: jdbc:mysql://192.168.88.51:3306/ynlj-third?characterEncoding=UTF-8&useUnicode=true&useSSL=false&connectTimeout=60000000&socketTimeout=1800000
          username: root
          password: jkauto@123lj
          driver-class-name: com.mysql.jdbc.Driver
        pg-db:
          url: jdbc:postgresql://192.168.70.14:10086/postgres?useUnicode=true&characterEncoding=UTF8
          username: postgres
          password: jkauto@123lj
          driver-class-name: org.postgresql.Driver

mybatis-plus:
  mapper-locations: classpath*:com/sonin/modules/**/xml/*Mapper.xml
  # 是否打印控制台
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl